// <auto-generated />
namespace DBStreet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class streetdbmigration5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(streetdbmigration5));
        
        string IMigrationMetadata.Id
        {
            get { return "202011191328372_streetdbmigration5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
